[project]
name = "ml-runner"
version = "0.0.1-alpha.1"
description = "Machine learning model runner for Linux, supporting a selection of ML models for VFX."
readme = "README.md"
requires-python = "==3.10.*"
dependencies = []

[dependency-groups]
dev = [
    "prek>=0.3.3",
    "ruff>=0.15.1",
]
